### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tythesly** [Sigourn/morrowind-improved#15]
Are you going to mark in the change log when you remove a mod due to incompatibility? Because I seen you removed a lot of mods and a couple looked interesting to me and I would like to use them still.

**Comment by LucasDelfino92** [comment]
Hi!
Yes, I definitely will. If a mod was remove because of a certain issue, be it bug or compatibility issue, it will be accompanied with a short explanation. Else, the mod was removed because it was not considered particularly "essential" to the overall game experience.
