### ISSUE TITLE
Broken link in main readme

### ISSUE THREAD

**Issue by tristansokol** [Sigourn/morrowind-improved#2]
Hi! Thanks for this great guide! 

I noticed the link at the bottom of the main readme appears to be broken. It seems like it should be a txt file of the order for mods, maybe just check it in github instead?

![image](https://user-images.githubusercontent.com/867661/81768184-fa673480-949f-11ea-9509-89c470e063c9.png)

**Comment by LucasDelfino92** [comment]
Fixed!
