### ISSUE TITLE
Question about tip

### ISSUE THREAD

**Issue by Tythesly** [Sigourn/morrowind-improved#20]
MWSEabotlib
Updated abot\lib.lua common file used by some of abot's mods.

If you've installed any of abot's Smart Journal, Smart Map, or Smart Ammo mods, you must install this file and allow it to overwrite the rest of them.

^How do I tell it to overwrite it because it doesn't pop up any option

**Comment by LucasDelfino92** [comment]
I'll change the wording; what I mean to say is that you must install this file and load it after the other (Smart Journal, Smart Map, Smart Ammo) mods to let its .lua file _override_ the rest.

**Comment by Tythesly** [comment]
Does the .lua file do this automatically or will it prompt me as some point in time?

**Comment by LucasDelfino92** [comment]
The .lua file works like pretty much other files (e.g. meshes, textures, etc.). Whenever abot updates the .lua file in one of his mods, he also updates the MWSEabotlib page with the new "master" .lua file his mods are compatible with.
