### ISSUE TITLE
Vanilla-flavoured Hair add on question

### ISSUE THREAD

**Issue by Tythesly** [Sigourn/morrowind-improved#27]
![image](https://user-images.githubusercontent.com/2800945/129433165-7513795e-6674-42ff-bcae-cebeadc2ce47.png)

https://www.nexusmods.com/morrowind/mods/49910?tab=files

Would I check both?

**Comment by LucasDelfino92** [comment]
The Vanilla option is all you need for the guide, but checking both won't hurt you in any way.
