### ISSUE TITLE
Maximalist mod order missing entries

### ISSUE THREAD

**Issue by Tythesly** [Sigourn/morrowind-improved#29]
GMST Menu Preset by Sigourn

GH Patches and Replacers 1.02

Aura 3.0 - Replacer

Bitter Coast Scum Replacer is way lower in the load order than in your guide (almost like it was option then changed to a definite?)

Weather Adjuster Preset by Sigourn

3d vines vanilla muschroom trees and ashmire replacer seem higher in the list than in the guide. Like they were later moved to optional in the guide but not the list?

**Comment by LucasDelfino92** [comment]
Fixed!
