### ISSUE TITLE
No tamriel_data section?

### ISSUE THREAD

**Issue by koppaf** [Sigourn/morrowind-improved#3]
Hi, seems like an awesome guide :) Thanks!

I tried clicking the tamriel_data section but the link seems broken?
(link: https://github.com/Sigourn/morrowind-improved/blob/master/modlist.md#tamriel_data)

MORROWIND IMPROVED
INDEX
Mending Morrowind
Tamriel_Data    <--------------
User interface

**Comment by LucasDelfino92** [comment]
Yep, I've removed it because it was only there to install a handful of mods that required Tamriel_Data, but since I've removed those mods then there's no point in having that section in anymore.
