### ISSUE TITLE
Change Log Archive?

### ISSUE THREAD

**Issue by Tythesly** [Sigourn/morrowind-improved#35]
Yo Sigourn! 

I had to take a break a bit from Morrowind and now I am back and you have made tons of changes since I last played!!! HOWEVER!

Its been a couple of months and the change log is missing a lot of your changes :O
I want to catch up with the last time I followed the guide (which was in September!) :(

How can I see all the changes you made since the change log currently only goes until December 3rd?

**Comment by LucasDelfino92** [comment]
I would strongly recommend you begin a new playthrough. The guide has chance a lot with many mods being removed and many mods being added.
