### ISSUE TITLE
Redundant entries in the Mod order

### ISSUE THREAD

**Issue by jksmilton** [Sigourn/morrowind-improved#36]
I noticed that in the mod order at the end of main.md that intelligent textures appears twice, I used the first position which seemed to work so I guess the second entry just needs removing?

Also the Magicka regeneration mod is still in the mod order list, though I can see you removed it in the changelog from the recommended mods.

**Comment by LucasDelfino92** [comment]
Thank you!
Fixed both main.md and addon.md.
