### ISSUE TITLE
Bug-Corrected and Enhanced Mods

### ISSUE THREAD

**Issue by wisp92** [Sigourn/morrowind-improved#40]
I wrote two mods that may replace the MWSE Clock Block and the MWSE part of the Speed and Movement Rebalanced:
[Clocks](https://www.nexusmods.com/morrowind/mods/50840)
[Sprinting](https://www.nexusmods.com/morrowind/mods/50839)

## Clocks
I didn't like that the MWSE Clock Block was lacking a hotkey to change between the two types of clocks and I also noticed that there is some inconsistency between that two clocks in 12-hour time regarding when the day period changes. Reading through its code I also noticed that it uses the enterFrame event a lot and the code it's kinda outdated.

### Features
1. It shows a game clock, real-time clock, or both above (or below) the compass.
2. You can cycle between the options using a customizable key (defaults to 'n').
3. You can choose between a 12-hour or 24-hour format in the MCM (I chose to represent noon by 'Noon', and midnight by 'MN' in the 12-hour format, but that can be easily changed.)

### Code Improvements
1. The game clock is updated only during simulation time at the rate of one a game second.
2. The real-time clock is updated continuously at a rate of a real-time minute.
3. All setting changes take effect the moment you exit the main menu (during the first second of the simulation).
4. The code works with in-game and real-time timestamps. This means it can be extended to show dates or anything else that is supported by the os.date function. The only reason I wrote some extra code for the 12-hour format was to make some small adjustments to the default format.

## Sprinting
The code of the Speed and Movement Rebalanced is not working properly. Specifically, the setZoom function is not called properly and it attempts to access tes3.mobilePlayer even in the main menu resulting in an error. I decided to fix these and enhanced the functionality greatly.

### Features
1. You can sprint when pressing a customizable key (defaults to 'LEFT ALT').
2. While sprinting you accelerate up to a maximum speed that is multiple of your current speed.
3. While sprinting your fatigue is decreasing fast. The fatigue drawback is reduced by your athletics down to a minimum value.
4. While sprinting the screen smoothly zooms in and it smoothly zooms out again when you stop.
5. If your fatigue reaches zero while sprinting you are safer a penalty. That is, you cannot sprint again for a short duration and/or until your fatigue reaches a required percentage. The penalty persists through save/load. Optionally you can also collapse from lack of fatigue (disabled by default).
6. You can choose to disable sprinting for any direction except the forward direction.

## Code Improvements
1.  Sprinting is only enabled while running by registering the function to the calcRunSpeed event.
2. The zooming functionality is controlled separately during the simulate event. Specifically, visualization can be registered to be performed and the system respects assigned priorities. This allows for more visualizations, e.g. shaking the screen when fatigue reaches zero, without too much effort.
3. The movements bindings are updated when leaving the menu.

I hope they are helpful. I tested them for a while but they are still in alpha versions. I'll be happy to fix any problems.

**Comment by LucasDelfino92** [comment]
Thank you for these!
I'll try them out in the future, and hopefully if no bugs are reported, I would be happy to include them.

**Comment by wisp92** [comment]
Can you give me some references regarding the  New Game Confirmation and Continue mods. I don't see any unfixed bugs on the mods' pages. They both seem to be inactive for the last 2 to 3 years. I can try to rewrite them using the latest MWSE libraries and see if the problems are solved. I can then contact the authors in case they want to update them or just publish them in Nexus as alternatives since both plugins do not have any permission restrictions.

**Comment by LucasDelfino92** [comment]
Sure. These are the bug reports I've heard about. Mind you, I've never encountered them myself...

1) **Can't create a new game when starting up the game.** "When I start up the game, it will not let me create a new game.  I just click on it.  and nothing.  lol  the same if I exit out.  Though all the other functions work."

"When I click New, I hear the button press sound and it changes color. When I click exit, the color changes but the sound does not play. All the other buttons work properly."

2) **Game freeze when using New Game Confirmation alongside Chargen Revamped - Expanded Lands.** "When I used CREL, my main menu would freeze whenever I clicked any of the buttons, and force me to alt-tab away and exit the window. I posted it here, the first suggestion was to remove New Game Confirmation due to a bunch of similar reports in the past, and it fixed my problem."

3) **Game freezing with Continue**. "Continue for me has a tendency to freeze when loading into a game, sometimes by throwing up erroneous error messages that aren't there if I load the game normally, and not letting me click through it, hanging the game on it"

**Comment by wisp92** [comment]
I finished with New Game Confirmation. Without having these bugs myself or the log files it's impossible to know if they are solved or not. I rewrote the code in a way that eventually the original handler is used, and I added to more conditions that ensure the code is running only in the Main Menu, and before the game simulation started. If users still have problems with it's most probably because their MWSE installation is faulty.

I'll contact the author in case they are interested to update their files; otherwise, I'll post it as a new mod. In the meantime, here are the files in case you want to add them to the guide as optional:

[Wisp's New Game Confirmation.zip](https://github.com/Sigourn/morrowind-sharp/files/8197887/Wisp.s.New.Game.Confirmation.zip)

**Comment by LucasDelfino92** [comment]
Thank you! I've posted a link to your comment in the Morrowind Modding Community Discord. Hopefully that will give it some traction and get more testers.

**Comment by wisp92** [comment]
Thank you! I didn't realize one thing though, that the New Game entry by default appears even during the game (I forgot it gets removed from the Continue mod). So I think should make some adjustments to the conditions to work well for users who don't use this option. When it's done I'll post it here again. I hope there is a way to update the file in the link.

EDIT: Actually I think it will work in that case out of the box as well. One condition is redundant, but it shouldn't cause any problems. I'll leave it to the testers.

**Comment by wisp92** [comment]
I rewrote both of them and combined them in a new mod: [Improved Main Menu](https://www.nexusmods.com/morrowind/mods/50856/). The Main Menu is very tricky to work with. I tried to be the least intrusive possible to each original code in order to avoid complications but we will see. I'll post it in the discord too.

**Comment by LucasDelfino92** [comment]
You will want to reupload the mod as you accidentally included config files for all mods you were apparently using. :smile:

**Comment by wisp92** [comment]
Oops! That's what 2 days of modding do. Thank you very much. It's fixed now.

**Comment by LucasDelfino92** [comment]
The guide features all these mods now.
