### ISSUE TITLE
distant statics override update

### ISSUE THREAD

**Issue by Necrolesian** [Sigourn/morrowind-improved#42]
the version of the distant statics override files linked in setup.md is old
version 2.0.1 fixes an issue related to the vivec cantons

https://www.dropbox.com/s/9rgwv9yjbipp5gi/Abot%20Distant%20Statics%20Overrides%20-%20Necro%20Edit%202.0.1.7z?dl=1

**Comment by LucasDelfino92** [comment]
Thank you! Linked to that file instead.
