### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sightergoliant** [Sigourn/morrowind-improved#43]
The additional MCP configurations available, mentioned throughout the main document, seems to point in the wrong direction.

https://github.com/Sigourn/morrowindsharp/blob/master/main2.md#additional-mcp-patches

It should be main.md and not main2.md, I believe, but I'm not certain.

https://github.com/Sigourn/morrowindsharp/blob/master/main.md#additional-mcp-patches

Hope this is the right way to bring this to your attention. This is literally my first day on github and my first-ever comment on anything, so I don't know if I'm doing this according to the normal community guidelines for submitting issues.

**Comment by LucasDelfino92** [comment]
Thank you very much! Just fixed it.
