### ISSUE TITLE
Here Comes the Sun... Glare incorrect link

### ISSUE THREAD

**Issue by OwenCropper** [Sigourn/morrowind-improved#46]
The link to Here Comes the Sun... Glare under the Visuals section leads to a different mod called Better Sun. This creates some confusion on which is the correct mod that needs to be downloaded. I also thought it would be worthwhile to note that inside modlist.txt from Morrowind Sharp MO2 Profile Files has Here Comes the Sun... Glare listed instead of Better Sun, just incase if Better Sun is the correct mod.

**Comment by LucasDelfino92** [comment]
Thank you for spotting this. Fixed the link. The intended mod is indeed Here Comes the Sun... Glare.
