### ISSUE TITLE
Small Typo and two Questions

### ISSUE THREAD

**Issue by Shanl3y** [Sigourn/morrowind-improved#47]
-On the Setup page your refer twice to New Vegas
-When starting Whyre Mash there are lots of inactive mods, is that intended?
-In Whyre Mesh theres only one mod that needs it's master to be updated, ist that correct?

**Comment by Shanl3y** [comment]
Also when installing the Morrowind Sharp profile files the following three mods have a different default name in your modlist.txt compared to the default when installing trough MO2, which disables them in MO2. Maybe make it more apparent that those three mods need to have their name changed when installing.
-Calculated List Fix -> UNCALCULATED LEVELED CREATURES FIX AND YOU CAN ACTUALLY GET ENCHANTED ARROWS AFTER LEVEL 5
-Services Restored -> Half11's Misc Mods
-Complete Armor Joints -> Complete_Armor_joints

**Comment by Shanl3y** [comment]
Accidentally closed the issue.

**Comment by LucasDelfino92** [comment]
Just fixed the references to New Vegas.
I'm not sure what are these many inactive mods you mention.
It's possible that there's only one mod that needs their masters updated, they are in the minority.

I'll check out those mod names now!

**Comment by LucasDelfino92** [comment]
Mod names fixed and instructions updated for Half11's Misc Mods.

**Comment by Shanl3y** [comment]
Thanks for the update and all the hard work!
