### ISSUE TITLE
Which version to use for Alex's Better Fitted Female Armors?

### ISSUE THREAD

**Issue by MoTem** [Sigourn/morrowind-improved#48]
The latest version is 1.1, but the mod load order is for the older version.

**Comment by MoTem** [comment]
Further issues noted in modlist:

Missing Diseases Restored, Magicka Expanded, Enhanced Detection, Controlled Weapon Enchants.

**Comment by LucasDelfino92** [comment]
Thank you. These should all be fixed now. The listed version in the main guide is for 1.1 of Better Fitted Female Armors now.

**Comment by MoTem** [comment]
Great, thanks for the prompt response. And amazing work on the guide btw, Playing MW right now after installing the mods and having a blast.
