### ISSUE TITLE
fix: webhost for complete armor joints is down

### ISSUE THREAD

**Issue by memigh** [Sigourn/morrowind-improved#49]
https://mw.modhistory.com/file.php?id=12572 cannot be reached to access Complete Armor Joints

an archive was created in 2019:
https://web.archive.org/web/20161109210744/https://mw.modhistory.com/file.php?id=12572

thank you for the incredible modlist and comprehensive instructions

**Comment by LucasDelfino92** [comment]
Thank you, I just linked to an uploaded copy in GitHub.
