### ISSUE TITLE
MO2 Profile files of Hail Resdaynia

### ISSUE THREAD

**Issue by satorope** [Sigourn/morrowind-improved#51]
No link to MO2 Profile files of Hail Resdaynia.

**Comment by LucasDelfino92** [comment]
Fixed.

**Comment by satorope** [comment]
The URL is incorrect.

Wrong
https://github.com/Sigourn/morrowindsharp/raw/main/mods/Hail%20Resdaynia.7z.7z

Correct
https://github.com/Sigourn/morrowindsharp/raw/main/mods/Hail%20Resdaynia.7z

**Comment by LucasDelfino92** [comment]
Now truly fixed. Sorry.
