### ISSUE TITLE
Wouldn't it be better to rename the mod rather than merge it?

### ISSUE THREAD

**Issue by satorope** [Sigourn/morrowind-improved#52]
There are mods that are different versions of the main and optional mods.
And MO2 can be version checked and Morrowind mods are still updated.
For example, "AURA" was upgraded to version 5.3.2 today.
"Textures - MET" in "Project Atlas" is a patch for "Morrowind Enhanced Textures" and is not needed when not in use.
Wouldn't it be better to rename mods rather than merge them, like VivaNewVegas?

Morrowind Enhanced Textures: 5.2
MET Meshes: 1.2

Project Atlas: 7.1
Textures - MET: 7.1

**Comment by LucasDelfino92** [comment]
Just did this.
