### ISSUE TITLE
Wrye Mash 2021 - x64 - beta6

### ISSUE THREAD

**Issue by satorope** [Sigourn/morrowind-improved#54]
"Wrye Mash 2021 - x64 - beta6" is an independent package that does not require "Wrye Mash 2019 - x64".
If installed according to the guidelines, it will overwrite all files in "Wrye Mash 2019 - x64".
It would be less work to install only "Wrye Mash 2021 - x64 - beta6".

**Comment by LucasDelfino92** [comment]
Thank you for this, not sure why no one mentioned it before. Fixed.
