### ISSUE TITLE
Missing textures error

### ISSUE THREAD

**Issue by 7H3M4V3R1K** [Sigourn/morrowind-improved#58]
While generating distant lands the second time near the end of the guide, I got a message saying "missing texture: atl\atlas_velothi.dds
![Screenshot 2023-09-19 174503](https://github.com/Sigourn/morrowindsharp/assets/99099091/d9dbe232-c1d2-47b7-827d-a4f9de4aeb51)
" I didn't know what to do so I just continued and finished generation. Then in the game when I finished the guide and tried to enter a new game, I got another error: ![image](https://github.com/Sigourn/morrowindsharp/assets/99099091/44b17e43-5591-455e-a817-13aab89fec58) . I pressed yes to continue as I was only testing and the game continued, but I didn't test for long, I only walked around like 5 minutes max.

**Comment by LucasDelfino92** [comment]
The only thing I can think of about the first error is not following the instructions appropriately for the installation of Project Atlas and Glow in the Dahrk.

For the second, I believe you didn't uninstall the official plugins and their assets as instructed.

**Comment by 7H3M4V3R1K** [comment]
Well, yeah, I asked on the discord server and people said that. For the plugins, I didn't understand that I HAVE to uninstall them, as the way you've written it I thought you meant that it's better if we uninstall them but it's alright if we don't, but anyway I found a solution for that, the UMOPP and official plugins naturalized mods.

Otherwise, I could swear I followed your guide to the letter, so I have no idea where the project atlas problem came from.

**Comment by Evannee14** [comment]
I have the warning for Project Atlas missing texture too. I saw that atlas_velothi.dds now becomes two separated atlas_velothi_01.dds and atlas_velothi_02.dds. Could it be possible the mesh does not update the reference?

**Comment by LucasDelfino92** [comment]
I'm unable to reproduce the issue, unfortunately.
I've reworked the instructions for mods relying on Morrowind Optimization Patch and Project Atlas in hopes they are clearer to follow.

My suggestion is to uninstall the related mods, and follow the steps to install them and re-run Distant Land until you consistently hit the issue so I can reproduce it.

**Comment by LucasDelfino92** [comment]
I found the issue.
Project Atlas' Glow in the Dahrk Patch is not updated for Glow in the Dahrk.

Therefore, the solution is to simply skip the Project Atlas patch for that mod.
I'll modify the instructions accordingly and upload an updated mod order.

**Comment by 7H3M4V3R1K** [comment]
> I found the issue. Project Atlas' Glow in the Dahrk Patch is not updated for Glow in the Dahrk.
> 
> Therefore, the solution is to simply skip the Project Atlas patch for that mod. I'll modify the instructions accordingly and upload an updated mod order.

Alright, will do it ASAP. Thanks man for this amazing guide 🙏🏻
