### ISSUE TITLE
Higher Faction Requirements is too much

### ISSUE THREAD

**Issue by GreyWyvern** [Sigourn/morrowind-improved#6]
First of all, thanks so much for this guide! I've been playing Morrowind since a year or so after it was released. I've uninstalled and reinstalled it almost a dozen times and have to remod it each time. This guide was really helpful in getting a great Morrowind experience up and running with minimal fuss! Even if it does take a few hours to complete ;)

After running through the guide and getting my modded game up and running, the first JARRING roadblock I came across was with the Higher Faction Requirements mod. The issue with this mod is twofold:

a) Until you actually join a faction, there is NO indicator as to what skills or attributes in which you are falling short. You just get the message "you don't meet our requirements."

b) I believe the spirit of this guide is to introduce new players to what a great game Morrowind is by modding the graphics so it looks amazing, and modding the problems so it feels RIGHT; but this mod does NOT help in either of those regards. In all respects, Higher Faction Requirements is nothing but a "hardcore mode" mod for veteran players.

I built a new character with a custom class, chose "Combat" focus and still couldn't join the Fighter's guild without any specific explanation as to how I fell short. This is especially frustrating for vanilla and first-time players and it shouldn't be. I stress this because I recently pitched the game to a Morrowind-virgin friend who's going to blind-stream it using this Morrowind Improved mod list, and I know this mod is going to be a problem for him. I will certainly be recommending he disable this particular mod before doing the stream.

The first few quests for the Fighters Guild and most other factions are IDEAL for level 1 characters, and they shouldn't be locked out because a player chose an incompatible race or skill set. It might be a different argument if the Higher Faction Requirements mod kept level 1-3 rank requirements as they were and incrementally raised the rest, because by rank 4 or so you've probably joined at least two or three factions and have plenty of quests. But putting the hurdle even before rank 0 is too much of a change and IMHO doesn't fit the spirit of this modding guide.

**Comment by LucasDelfino92** [comment]
Thanks for the feedback!
Regarding Higher Faction Requirements: it's possible that the mod is a bit too much. That said, one can get the requirements of a given faction by talking to the NPC that lets you join the faction. With that out of the way, the gameplay section at least doesn't really account for new players. The guide itself was written as to clear any doubts, but  it was always designed with people who had already played the game in mind.

**Comment by LucasDelfino92** [comment]
Alternatively you can try out the higher faction requirements found in this mod's page.
https://www.nexusmods.com/morrowind/mods/47765
They are considerably more lenient.

**Comment by GreyWyvern** [comment]
> That said, one can get the requirements of a given faction by talking to the NPC that lets you join the faction.

All they really say is "We value [attribute] and [attribute], and [skill], [skill] and [skill]" but they don't reveal the required *values* AFAIK. That info you can only get once you're in the faction and see the tooltip by your rank. For example, my character had 50 Strength and 30 Endurance. I chose lots of "Fighter" related skills as majors and minors. When trying to join the Fighters Guild, while I know they value STR and END, I don't know *how* high I need to get them, nor if only my END is too low, or maybe *both* STR and END. Or what if my STR and END are fine and it's my skills that are too low???

That said, I see your point about this guide being for people who've already played the game and want to experience it in a new immersive way. I guess I only wanted to point out, since I'm shepherding a brand new player through the game soon, pretty much all of the other mods seemed just fine and helpful for a first time player except for this one.

And thanks! I'll take a look at some other options for this one.
