### ISSUE TITLE
Marksman Rebalanced MWS Config incomplete, mod doesn't work

### ISSUE THREAD

**Issue by DSeyka** [Sigourn/morrowind-improved#60]
[Marksman Rebalanced MWS Config](https://github.com/Sigourn/morrowindsharp/raw/main/mods/Marksman%20Rebalanced%20MWS%20Config.7z) consists of a single json entry ("minDistanceMultiplier":1.5) which leaves all other config options blank, therefore mod isn't even enabled when following the guide. To fix this, MWS config has to include all options, e.g.
```
{
  "maxDistanceMultiplier":"0.5",
  "minDistanceMultiplier":"1.5",
  "maxDistance":9000,
  "enableMod":true,
  "stealthMulti":"1.25"
}
```

**Comment by LucasDelfino92** [comment]
Is that so? I wasn't aware of it. Anyway I'll include it just to be safe. Thanks!
