### ISSUE TITLE
Suggestion: replace Waterfall Lights Remover with Waterfalls Tweaks

### ISSUE THREAD

**Issue by danaYatsuta** [Sigourn/morrowind-improved#65]
[Waterfalls Tweaks](https://www.nexusmods.com/morrowind/mods/46271) has the same functionality as Waterfalls Lights Remover, plus it resizes water splashes from waterfalls. It's designed to work with Better Waterfalls, and it's recommended on Better Waterfalls' nexus page as well.

**Comment by LucasDelfino92** [comment]
Thank you! I'll add it to the guide. Funny, it used to be part of it at one point.
